### ISSUE TITLE
version control in depth homework 3

### ISSUE THREAD

**Issue by FedorSannikov1988** [FedorSannikov1988/Immersion_in_Python_homework_4#1]
Привет .

Для того что бы сдать домашнее задание №3 по курсу "Контроль версий углублённо (GIT) (семинары)" прошу тебя:

-[1] Переименовать функцию transpose_matrix в transpose_matrix_v1 .

-[2]  Добавить функцию transpose_matrix_v2 выполняющую функции transpose_matrix_v1 использующую сторонний модуль (к примеру numpy)  для транспонирования матрицы . Вся необходимая информация по ссылке (метод1 - метод3): https://pythonist.ru/kak-transponirovat-matriczu-v-python/
-[3] Убрать из readme.md строчки: version control in-depth commit 1, version control in-depth commit 2, version control in-depth commit 3, version control in-depth commit 4 .

После выполнения прошу сделать pull request и перевести задачу обратно на меня .

**Comment by fedotoff144** [comment]
@FedorSannikov1988 task is done. please check my work
