### ISSUE TITLE
change file readme

### ISSUE THREAD

**Issue by FedorSannikov1988** [FedorSannikov1988/Immersion_in_Python_homework_4#3]
Привет .

-[1] Добавь в файл readme.md описание домашнего задания  к "Урок 3. Практики и инструменты для работы с Git"

pull requests в ветку [branch-for-pull-requests](https://github.com/FedorSannikov1988/Immersion_in_Python_homework_4/tree/branch-for-pull-requests)

**Comment by fedotoff144** [comment]
I closed this task

**Comment by FedorSannikov1988** [comment]
Проверил . Сойдет . Открывать заново задачу не буду .
