### ISSUE TITLE
again change file readme

### ISSUE THREAD

**Issue by FedorSannikov1988** [FedorSannikov1988/Immersion_in_Python_homework_4#5]
Прошу внести небольшие изменения в файл readme.md .

pull requests в ветку: [again-change-file-readme](https://github.com/FedorSannikov1988/Immersion_in_Python_homework_4/tree/again-change-file-readme)

**Comment by fedotoff144** [comment]
Task done

**Comment by FedorSannikov1988** [comment]
A perfectly executed job !
